server:
  http2:
    enabled: true

# Actuator
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

springdoc:
  swagger-ui:
    path: /doc
  show-actuator: true
  default-produces-media-type: application/json

spring:
  application:
    name: flow-translator-webapp

keip:
  namespaceMappings:
    - eipNamespace: integration
      xmlNamespace: http://www.springframework.org/schema/integration
      schemaLocation: classpath:org/springframework/integration/config/spring-integration.xsd
    - eipNamespace: file
      xmlNamespace: http://www.springframework.org/schema/integration/file
      schemaLocation: classpath:org/springframework/integration/file/config/spring-integration-file.xsd
    - eipNamespace: ftp
      xmlNamespace: http://www.springframework.org/schema/integration/ftp
      schemaLocation: classpath:org/springframework/integration/ftp/config/spring-integration-ftp.xsd
    - eipNamespace: groovy
      xmlNamespace: http://www.springframework.org/schema/integration/groovy
      schemaLocation: classpath:org/springframework/integration/groovy/config/spring-integration-groovy.xsd
    - eipNamespace: http
      xmlNamespace: http://www.springframework.org/schema/integration/http
      schemaLocation: classpath:org/springframework/integration/http/config/spring-integration-http.xsd
    - eipNamespace: jms
      xmlNamespace: http://www.springframework.org/schema/integration/jms
      schemaLocation: classpath:org/springframework/integration/jms/config/spring-integration-jms.xsd
    - eipNamespace: kafka
      xmlNamespace: http://www.springframework.org/schema/integration/kafka
      schemaLocation: classpath:org/springframework/integration/kafka/config/spring-integration-kafka.xsd
    - eipNamespace: mqtt
      xmlNamespace: http://www.springframework.org/schema/integration/mqtt
      schemaLocation: classpath:org/springframework/integration/mqtt/config/spring-integration-mqtt.xsd
    - eipNamespace: sftp
      xmlNamespace: http://www.springframework.org/schema/integration/sftp
      schemaLocation: classpath:org/springframework/integration/sftp/config/spring-integration-sftp.xsd
    - eipNamespace: tcp-udp
      xmlNamespace: http://www.springframework.org/schema/integration/ip
      schemaLocation: classpath:org/springframework/integration/ip/config/spring-integration-ip.xsd
    - eipNamespace: ws
      xmlNamespace: http://www.springframework.org/schema/integration/ws
      schemaLocation: classpath:org/springframework/integration/ws/config/spring-integration-ws.xsd
    - eipNamespace: int-xml
      xmlNamespace: http://www.springframework.org/schema/integration/xml
      schemaLocation: classpath:org/springframework/integration/xml/config/spring-integration-xml.xsd
